### ISSUE TITLE
Crafthead retrieves old skin instead of the newer one

### ISSUE THREAD

**Issue by owosrl** [astei/crafthead#39]
I'm using crafthead with essentialsx discord and I noticed that crafthead retrieves my old skin, if I use mojang apis, it retrieves the newer one

[Old image](https://textures.minecraft.net/texture/4342a6ff712674b52b138d9860ba11bbc5ae1e2804b10f8c73bdef8414ff1786):  
![image](https://user-images.githubusercontent.com/31825825/152688943-01f76c55-b2a4-462d-a107-68d1c80c1bbc.png)

[New image](https://crafthead.net/skin/8b63d6df4e7e412b857278cbbd93ece5):  
![image](https://user-images.githubusercontent.com/31825825/152688951-f9b7f819-a450-4729-9417-54a49205bf69.png)

**Comment by astei** [comment]
Yikes - turns out this was because during some refactoring I forgot to add TTLs to the Cloudflare KV that we use as the primary cache for Crafthead.

In 4581cb7c33612ed4de6c632b224ce21d79b263f4 I've added in expiry (it will now expire 24 hours after fetch). I have also purged the live production cache, so your skin should now be visible.
